networks:
  scooter:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo:7
    ports:
      - "27017:27017"
    networks:
      - scooter
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - scooter
    env_file:
      - .env
    depends_on:
      - mongo

  admin-dashboard:
    container_name: admin-dashboard
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - scooter
    env_file:
      - .env

  web-app:
    container_name: web-app
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - scooter
    env_file:
      - .env

  mobile-app:
    container_name: mobile-app
    build:
      context: ./mobile-app
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - scooter
    env_file:
      - .env

  simulation:
    container_name: simulation
    build:
      context: ./simulation
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - scooter
    env_file:
      - .env
    volumes:
      - ./city-data:/city-data:ro

volumes:
  mongo-data:
