networks:
  scooter:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo:7
    ports:
      - "27017:27017"
    networks:
      - scooter
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - scooter
    env_file:
      - .env
    depends_on:
      - mongo

  admin-webclient:
    container_name: admin-webclient
    build:
      context: ./admin-webclient
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - scooter
    env_file:
      - .env

  webclient:
    container_name: webclient
    build:
      context: ./webclient
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - scooter
    env_file:
      - .env

  mobileclient:
    container_name: mobileclient
    build:
      context: ./mobileclient
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - scooter
    env_file:
      - .env

  simulation:
    container_name: simulation
    build:
      context: ./simulation
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - scooter
    env_file:
      - .env
    volumes:
      - ./city-data:/city-data:ro

volumes:
  mongo-data: